# Search
search: 
  enable: true
  service: hexo # google/hexo/algolia/azure/baidu
  # google 
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:

# friends link
links:
- name: GitHub
  url: https://github.com/zerox-v
- name: CnBlogs
  url: https://www.cnblogs.com/ismars


# navigation menu
menu:
  - name: Home
    slug: home
    url: /
  - name: Archives
    slug: archives
    url: /archives
  - name: About
    slug: about
    url: /about
  - name: AI 助手
    slug: chat-ai
    url: https://ai.ionic.fun

# widgets
widgets:
  - about
  - links
  - categories
  - tagcloud

# Less
less:
  compress: true

# use url, not username
social:
- slug: github
  url: https://github.com/zerox-v
- slug: twitter
  url: https://www.cnblogs.com/ismars
- slug: rss
	url: /atom.xml
